### ISSUE TITLE
Cost-model panic when loading savings page

### ISSUE THREAD

**Issue by leosunmo** [kubecost/cost-model#180]
```kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 2019/10/11 01:37:24 http: panic serving 172.22.61.70:58616: interface conversion: interface {} is nil, not map[string]interface {}
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model goroutine 20032 [running]:
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model net/http.(*conn).serve.func1(0xc00093af00)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/net/http/server.go:1769 +0x139
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model panic(0x1cf6cc0, 0xc009fccab0)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model github.com/kubecost/cost-model/costmodel.labelsFromPrometheusQuery(0x1c812a0, 0xc009fcca50, 0xc0077ca000, 0x4d0fd, 0x1c812a0)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/app/costmodel/costmodel.go:694 +0x988
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model github.com/kubecost/cost-model/costmodel.findDeletedPodInfo(0x237a300, 0xc00041a800, 0xc008865b98, 0xc002b97a5e, 0x2, 0x0, 0x0)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/app/costmodel/costmodel.go:672 +0x356
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model github.com/kubecost/cost-model/costmodel.(*CostModel).ComputeCostData(0xc001828000, 0x237a300, 0xc00041a800, 0x23f4f20, 0xc0000e6000, 0x23e2780, 0xc0005dca20, 0xc002b97a5e, 0x2, 0x0, ...)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/app/costmodel/costmodel.go:651 +0x5683
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model main.(*Accesses).CostDataModel(0xc000189ee0, 0x239cc40, 0xc000e3c460, 0xc001e0e300, 0x0, 0x0, 0x0)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/app/main.go:147 +0x412
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000bf8c00, 0x239cc40, 0xc000e3c460, 0xc001e0e300)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x948
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model net/http.(*ServeMux).ServeHTTP(0xc000bf8c80, 0x239cc40, 0xc000e3c460, 0xc001e0e300)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/net/http/server.go:2375 +0x1d6
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model net/http.serverHandler.ServeHTTP(0xc0028bc1a0, 0x239cc40, 0xc000e3c460, 0xc001e0e300)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/net/http/server.go:2774 +0xa8
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model net/http.(*conn).serve(0xc00093af00, 0x23a4140, 0xc00c584900)
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/net/http/server.go:1878 +0x851
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model created by net/http.(*Server).Serve
kubecost-cost-analyzer-bb4ccf969-bgmnh cost-model 	/usr/local/go/src/net/http/server.go:2884 +0x2f4```

**Comment by AjayTripathy** [comment]
Hi @leosunmo can you please provide the version you're running here? This should be fixed in 1.45.2, released yesterday.

**Comment by leosunmo** [comment]
This is 1.44.4. Will upgrade ASAP.

**Comment by dwbrown2** [comment]
Leo, just wanted to double check to make sure this isn't still happening for you. Let me know if we can help!

**Comment by dwbrown2** [comment]
@leosunmo going to go ahead and close for now, but please reopen if this is still occurring or if we can get you anything else!

**Comment by leosunmo** [comment]
This issue doesn't seem to occur anymore
