### ISSUE TITLE
Certain UI elements not loading when they are no PVs in the cluster

### ISSUE THREAD

**Issue by immusk** [kubecost/cost-model#263]
Hi @dwbrown2 

`xx.xx.xx.xx - - [30/Dec/2019:03:15:43 +0000] "GET /metrics HTTP/1.1" 404 153 "-" "Prometheus/2.3.2" "-"
2019/12/30 03:15:43 [error] 8#8: *535 open() "/var/www/metrics" failed (2: No such file or directory), client: xx.xx.xx.xx, server: _, request: "GET /metrics HTTP/1.1", host: "xx.xx.xx.xx:9090"`

seeing this error continuously on `cost-analyzer-frontend` , can you please help here to get out of this.

**Comment by dwbrown2** [comment]
Hi @immusk, when did this issue start occurring? Also, what app version are you currently running?

**Comment by immusk** [comment]
I noticed container is getting restarted, when I tailed logs I found the above error in log
I am using this version: `Kubecost v1.49.3`

@dwbrown2 I even need some other information related to `0.2Gi` storage that we are attaching.
can I know what actually we are storing in this, why is it needed?

# Define persistence volume for cost-analyzer
persistentVolume:
  size: 2Gi
  enabled: true # Note that setting this to false means configurations will be wiped out on pod restart.

can you please give more info on it. what configurations will be missed on pod restarts.

**Comment by dwbrown2** [comment]
@AjayTripathy is investigating this error. 

Our PV is used to store all of the configuration options exposed in Settings (e.g. model settings, default labels, etc)

**Comment by AjayTripathy** [comment]
Hi @immusk , we're unable to recreate a 404 to /metrics on our end. Are you using an ingress to reach that URL or the app? If so, could we see the ingress definition?

**Comment by dwbrown2** [comment]
@immusk is still outstanding or were you able to get it resolved? let us know if we can help.

**Comment by immusk** [comment]
@dwbrown2 that issue is resolved, but I am facing the below issue all the time.
below dashboards are taking more time to load and sometimes this keep onn in pending state, can you help here, how to get this quick?

<img width="1457" alt="Screenshot 2020-02-03 at 5 42 38 PM" src="https://user-images.githubusercontent.com/8833971/73653118-7803f300-46ae-11ea-89ac-2d337eb4a288.png">
<img width="1675" alt="Screenshot 2020-02-03 at 5 55 46 PM" src="https://user-images.githubusercontent.com/8833971/73653119-789c8980-46ae-11ea-9bb6-5effff059654.png">

**Comment by dwbrown2** [comment]
Hi @immusk, happy to help here. Can you share more context please?

* What version are you running? Can you please upgrade to latest if possible to confirm this is still occurring? 
* Can you sort this network view you shared by greatest to least _time_? This will give us a better sense of whats going on.
* Can you confirm this is occurring when you port-forward directly to the pod? I want to make sure it's not caused by a networking issue.

**Comment by immusk** [comment]
Hi @dwbrown2 

currently its is running with 1.46.0
I will first try to update it, and will let you know.

I have question regarding update - what actually I should update - I mean just updating the docker images to the latest of yours is fine? or else what else should I check and update.

**Comment by dwbrown2** [comment]
It depends on how you installed. Should just be a simple Helm upgrade if you installed with our default path. More info here https://kubecost.com/install

**Comment by immusk** [comment]
@dwbrown2  I have upgraded the kubecost to 1.51.1 verison.
and after upgrading everything is failing 😢 
No dashboad is loading.
Please help
attached the images.
<img width="1680" alt="Screenshot 2020-02-06 at 7 23 05 PM" src="https://user-images.githubusercontent.com/8833971/73943351-9ec46280-4916-11ea-9076-47d69aa77c9a.png">
<img width="1677" alt="Screenshot 2020-02-06 at 7 23 54 PM" src="https://user-images.githubusercontent.com/8833971/73943363-a257e980-4916-11ea-828e-0e4f328a561c.png">
<img width="1680" alt="Screenshot 2020-02-06 at 7 24 14 PM" src="https://user-images.githubusercontent.com/8833971/73943368-a3891680-4916-11ea-9d7a-38f4283ce9b2.png">
<img width="1680" alt="Screenshot 2020-02-06 at 7 24 33 PM" src="https://user-images.githubusercontent.com/8833971/73943371-a421ad00-4916-11ea-8964-5373f6c28390.png">
<img width="1241" alt="Screenshot 2020-02-06 at 7 24 59 PM" src="https://user-images.githubusercontent.com/8833971/73943372-a4ba4380-4916-11ea-9e13-ed75430329bc.png">

**Comment by dwbrown2** [comment]
Hi @immusk, the fact that you are getting a 404 on our core endpoints means that something is amiss in your deployment. Would this potentially be due to your ingress or other networking restrictions? 

The best way for us to help troubleshoot this would be to capture a bug report. http://docs.kubecost.com/bug-report

**Comment by immusk** [comment]
@dwbrown2 actually its was issue from my side, I have successfully updated it to 1.51.1 version.
But still I am noticing the same issue as this 
https://github.com/kubecost/cost-model/issues/263#issuecomment-581391302
3 aggregates are failing with the same issue and its taking more time to load.

**Comment by dwbrown2** [comment]
@immusk would you be able to upgrade to our latest release (currently 1.51.2) and then send us a [bug report](http://docs.kubecost.com/bug-report)? It would also be really helpful to see what errors/warnings are present in your Javascript console. We should hopefully be able to quickly identify what is going on here.

**Comment by immusk** [comment]
@dwbrown2  @AjayTripathy 
facing this issue, where I already have kube state metrics version running with specified version
`  containers:
      - image: quay.io/coreos/kube-state-metrics:v1.6.0
        imagePullPolicy: IfNotPresent
        name: prometheus-kube-state-metrics
`
even I tried updating  to higher versions still facing this issue.
updated the details in the screenshot.

and I am currently using 15.2.2 version which is latest too.

**Comment by dwbrown2** [comment]
@immusk are you able to send us a bug report to team@kubecost.com? http://docs.kubecost.com/bug-report

**Comment by dwbrown2** [comment]
Responded via email. This has to do with a custom/unbundled Prometheus that does not have ksm metrics that are expected.

**Comment by immusk** [comment]
@dwbrown2  noticing that kubecost is giving some wrong information on pvc cost calculations.
1. It is showing more cost than what we see the actual cost information from our cloud providers.
2. It is showing low cost on few aws k8s clusters(our own setup of k8s clusters on ec2 instances) and on few it is showing huge costs with difference of around 800$
3.  same with azure too on few azure k8s clusters(our own setup of k8s clusters on azure vm's) and on few it is showing huge costs with difference.

we have calculated the actual cost from cloud providers, and cost that kubecost gives.
But the actual difference we are getting is from PVC's.
we are using OPENEBS as our persistent volumes, these OPENEBS pods cost are pricing as too huge.
please find the example screen shots.
please help here to resolve these differences

<img width="1208" alt="Screenshot 2020-02-28 at 8 55 55 AM" src="https://user-images.githubusercontent.com/8833971/75507859-4578bc00-5a08-11ea-9996-2f486309db96.png">
<img width="1209" alt="Screenshot 2020-02-28 at 8 56 36 AM" src="https://user-images.githubusercontent.com/8833971/75507866-49a4d980-5a08-11ea-9409-a74dc07e97ab.png">

**Comment by dwbrown2** [comment]
Hi @immusk! Can we please create a new Github issue for this and can you please upgrade to v1.53.1 and confirm this is still happening? 

We just patched an Azure PV issue: https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.53.1

**Comment by dwbrown2** [comment]
Passing to Niko, because he was reviewing this.

**Comment by dwbrown2** [comment]
@immusk this is has now gone out to production, anything else we can get you here?

**Comment by immusk** [comment]
@dwbrown2 I am still seeing the high costs for the pvc's not seeing any difference in costs even after updating to the latest version.

**Comment by immusk** [comment]
I have deployed this in 2 different k8s clusters, it is working fine on one cluster, where costs are low which shows as expected and on another cluster it is huge for both aws and azure.

**Comment by dwbrown2** [comment]
Hi @immusk, I believe this https://github.com/kubecost/cost-model/issues/363#issuecomment-596347180 applies to your situation. Let's continue the discussion on that issue.
