### ISSUE TITLE
Support assuming an IAM role with Kubernetes Service Account

### ISSUE THREAD

**Issue by gopisaba** [kubecost/cost-model#266]
I am trying to use IAM role associated to the Kubernetes Service Account `kubecost-cost-analyzer` which has access to the spot instance data feed s3 bucket but it is NOT working.

```
I0103 15:12:33.337123       1 awsprovider.go:684] Skipping AWS spot data download: AccessDenied: Access Denied
	status code: 403, request id: C00AC2F2BFA0604C, host id: Ee4qJHCmBeznD/mqbFjQ/d1Ls1sLzK3NrGxMLGIOB8R/n9HQARcOYxCb1C47oOXL/8uuqFkm6OI=
```

To support this feature, the aws sdk has to be upgraded to `>=1.23.13`. Is it possible to upgrade them?

*Reference URLs*
[iam-roles-for-service-accounts-minimum-sdk](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)
[iam-roles-for-service-accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

**Comment by dwbrown2** [comment]
Thanks for this issue, Gopinath. Assigning to @AjayTripathy for investigation.

**Comment by AjayTripathy** [comment]
Hi @gopisaba, we should be able to support this! I’ll look at upgrading this version soon. Is this for use with the paid or free version of Kubecost?

**Comment by gopisaba** [comment]
@AjayTripathy, this is for the free version of Kubecost. Thanks!

**Comment by ChienHuey** [comment]
My org is currently evaluating KubeCost but would be using this feature for the paid version (Business or higher) if/when we adopt it.

**Comment by dwbrown2** [comment]
This is now prioritized during our next sprint!

**Comment by dwbrown2** [comment]
Thanks for this upgrade, @AjayTripathy! Any additional work needed here?

**Comment by AjayTripathy** [comment]
This is complete with all our integration + regression tests pass. I was also able to do a set of simple tests and so I believe this task is sufficiently complete. I haven’t historically used this as an authentication mechanism so it would be really helpful if anybody is able to help verify in our next build or review #302

**Comment by gopisaba** [comment]
Updated the helm chart with 1.51.1. still seeing the access denied messages 
```
kubecost-cost-analyzer-79f8664597-gnjdl cost-model I0204 22:52:49.456323       1 awsprovider.go:694] Skipping AWS spot data download: AccessDenied: Access Denied
kubecost-cost-analyzer-79f8664597-gnjdl cost-model 	status code: 403, request id: F8E373624DBAE252, host id: 4XYNcoCt1o0c19ENTivppQQ3vT5G31HptT3i56uXA9h0xY4rSQph4MTrL7SWV9XoyDg3Ti0Vvis=
kubecost-cost-analyzer-79f8664597-gnjdl cost-analyzer-frontend 100.64.3.226 - - [04/Feb/2020:22:52:49 +0000] "POST /model/updateSpotInfoConfigs HTTP/1.1" 200 905 "https://kubecost-cost-analyzer/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "172.21.177.128, 100.64.66.93"
```

**Comment by AjayTripathy** [comment]
This didn't make it out until version 1.51.2 -- can you try that build?

Additionally, in order for spot data to work, you will need to upload bucket name/region and the optional prefix if your bucket is using it, but the service key name and service key value will need to be left blank.

**Comment by dwbrown2** [comment]
i believe i've heard other reports of users leveraging this approach for applying a role. @gopisaba is this working as expected now for you?

**Comment by sppwf** [comment]
Hi @dwbrown2 
It does not work for me. I am using 1.54 version of the app

some logs 

2020/03/24 10:42:57 error getting disks: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment
2020/03/24 10:42:57 error getting disks: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment
2020/03/24 10:42:57 error getting disks: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment

Also, could you please guys update Helm chart to support adding Annotations to cost-analyzer Service Account?

Thanks
Sergiu Plotnicu

**Comment by AjayTripathy** [comment]
Hi @sppwf , we were able to reproduce this issue generating those error logs and will have a fix in our next release. I've filed https://github.com/kubecost/cost-analyzer-helm-chart/issues/362 to track the request to make this easier to do by annotating our service account at install time.

**Comment by AjayTripathy** [comment]
Here are the steps I took to repro. 
1. I created an OIDC provider for an eks cluster: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
2. I created an IAM role using the AWS console with ec2.DescribeVolumes and s3.List and s3.Read permissions: https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html
3.  I annotated the kubecost service account with the name of the IAM role manually

**Comment by AjayTripathy** [comment]
This should be fixed in our latest release, 1.56.0!

**Comment by sppwf** [comment]
Hi,

I still receive some error - missing OpenID prodvider, however i have it in IAM:
```
2020/04/09 10:10:17 error getting disks: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: 506dceba-01d9-4f3c-b7a8-181a809ba5fb
2020/04/09 10:10:17 error getting disks: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/XXXXXxxxxxx
        status code: 400, request id: 5cb7aeb3-f4c2-44a8-ab56-75560b9e9764
```
tried - next version
```
helm ls -n kubecost
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubecost        kubecost        2               2020-04-09 12:26:30.492078 +0300 EEST   deployed        cost-analyzer-1.56.1    1.56.1
```

**Comment by AjayTripathy** [comment]
Hi @sppwf , I was unable to reproduce. Can you run 

`aws eks describe-cluster --name cluster_name --query "cluster.identity.oidc.issuer" --output text
` ? Does that successfully return the OIDC provider? And can you confirm the trust relationship has been correctly set up on the IAM role? (https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html step 11 here under the AWS management console.)

**Comment by dwbrown2** [comment]
We now have a number of users leveraging this functionality. 

@gopisaba is there anything else we can do to help? If not, I'll close this issue.

**Comment by gopisaba** [comment]
Thanks for adding this functionality.

**Comment by marcportabellaclotet-mt** [comment]
Thanks dwbrown2, it is also working for us.

Is it possible to add iam role k8s service account support for the optional module that can be configured to find abandoned load balancers and disks.?
On this module, I receive the message : ``` unable to get addresses: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment``` 

Thanks for such a great tool.

**Comment by AjayTripathy** [comment]
Hi @marcportabellaclotet-mt , looks like that module hasn't been updated in some time and needs additional work to use the newer authentication flows and be made useful. I've filed https://github.com/kubecost/cost-model/issues/794 to take a look
